export const USER_ACTIONS = {
    REQUEST: "USER_REQUEST",
    FETCH_LIST_SUCCESS: "USER_FETCH_LIST_SUCCESS",
    FETCH_ALL_SUCCESS: "USER_FETCH_ALL_SUCCESS",
    CREATE_SUCCESS: "USER_CREATE_SUCCESS",
    UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
    DELETE_SUCCESS: "USER_DELETE_SUCCESS",
    FAILURE: "USER_FAILURE",
    ERROR: "USER_ERROR"
};
