export const ROLE_ACTIONS = {
    REQUEST: "ROLE_REQUEST",
    FETCH_LIST_SUCCESS: "ROLE_FETCH_SUCCESS",
    FETCH_ALL_SUCCESS: "FETCH_ALL_SUCCESS",
    CREATE_SUCCESS: "ROLE_CREATE_SUCCESS",
    UPDATE_SUCCESS: "ROLE_UPDATE_SUCCESS",
    DELETE_SUCCESS: "ROLE_DELETE_SUCCESS",
    FAILURE: "ROLE_FAILURE",
    ERROR: "ROLE_ERROR"
};
