export const ACTION_ACTIONS = {
    REQUEST: "ACTION_REQUEST",
    FETCH_SUCCESS: "ACTION_FETCH_SUCCESS",
    CREATE_SUCCESS: "ACTION_CREATE_SUCCESS",
    UPDATE_SUCCESS: "ACTION_UPDATE_SUCCESS",
    DELETE_SUCCESS: "ACTION_DELETE_SUCCESS",
    FAILURE: "ACTION_FAILURE",
    ERROR: "ACTION_ERROR"
};
