export const PERMISSION_ACTIONS = {
    REQUEST: "PERM_REQUEST",
    FETCH_SUCCESS: "PERM_FETCH_SUCCESS",
    FETCH_ALL_PERM_SUCCESS: "PERM_FETCH_ALL_SUCCESS",
    CREATE_SUCCESS: "PERM_CREATE_SUCCESS",
    UPDATE_SUCCESS: "PERM_UPDATE_SUCCESS",
    DELETE_SUCCESS: "PERM_DELETE_SUCCESS",
    FAILURE: "PERM_FAILURE",
    ERROR: "PERM_ERROR"
};
