export const GRANT_ACTIONS = {
    REQUEST: "GRANT_REQUEST",
    FETCH_SUCCESS: "GRANT_FETCH_SUCCESS",
    CREATE_SUCCESS: "GRANT_CREATE_SUCCESS",
    UPDATE_SUCCESS: "GRANT_UPDATE_SUCCESS",
    DELETE_SUCCESS: "GRANT_DELETE_SUCCESS",
    FAILURE: "GRANT_FAILURE",
    ERROR: "GRANT_ERROR"
};
