export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_ACTIONS = {
    REQUEST: "USER_LOGIN_REQUEST",
    SUCCESS: "USER_LOGIN_SUCCESS",
    ERROR: "USER_LOGIN_ERROR",
    FAILURE: "USER_LOGIN_FAILURE"
};
