export const RESOURCE_ACTIONS = {
    REQUEST: "RESOURCE_REQUEST",
    FETCH_SUCCESS: "RESOURCE_FETCH_SUCCESS",
    CREATE_SUCCESS: "RESOURCE_CREATE_SUCCESS",
    UPDATE_SUCCESS: "RESOURCE_UPDATE_SUCCESS",
    DELETE_SUCCESS: "RESOURCE_DELETE_SUCCESS",
    FAILURE: "RESOURCE_FAILURE",
    ERROR: "RESOURCE_ERROR"
};
